/* location */
INSERT INTO location VALUES (57, NULL);
INSERT INTO location VALUES (83, NULL);
INSERT INTO location VALUES (84, NULL);
INSERT INTO location VALUES (85, NULL);
INSERT INTO location VALUES (86, NULL);
INSERT INTO location VALUES (87, NULL);
INSERT INTO location VALUES (88, NULL);
INSERT INTO location VALUES (89, NULL);
INSERT INTO location VALUES (90, NULL);
INSERT INTO location VALUES (91, NULL);
INSERT INTO location VALUES (92, NULL);
INSERT INTO location VALUES (93, NULL);
INSERT INTO location VALUES (94, NULL);
INSERT INTO location VALUES (95, NULL);
INSERT INTO location VALUES (96, NULL);
INSERT INTO location VALUES (97, NULL);
INSERT INTO location VALUES (98, NULL);
INSERT INTO location VALUES (99, NULL);
INSERT INTO location VALUES (100, NULL);
INSERT INTO location VALUES (1, 1);
INSERT INTO location VALUES (2, 2);
INSERT INTO location VALUES (3, 3);
INSERT INTO location VALUES (4, 4);
INSERT INTO location VALUES (5, 5);
INSERT INTO location VALUES (6, 6);
INSERT INTO location VALUES (7, 7);
INSERT INTO location VALUES (8, 8);
INSERT INTO location VALUES (9, 9);
INSERT INTO location VALUES (10, 10);
INSERT INTO location VALUES (11, 11);
INSERT INTO location VALUES (12, 12);
INSERT INTO location VALUES (13, 13);
INSERT INTO location VALUES (14, 14);
INSERT INTO location VALUES (15, 15);
INSERT INTO location VALUES (16, 16);
INSERT INTO location VALUES (17, 17);
INSERT INTO location VALUES (18, 18);
INSERT INTO location VALUES (19, 19);
INSERT INTO location VALUES (20, 20);
INSERT INTO location VALUES (21, 21);
INSERT INTO location VALUES (22, 22);
INSERT INTO location VALUES (23, 23);
INSERT INTO location VALUES (24, 24);
INSERT INTO location VALUES (25, 25);
INSERT INTO location VALUES (26, 26);
INSERT INTO location VALUES (27, 27);
INSERT INTO location VALUES (28, 28);
INSERT INTO location VALUES (29, 29);
INSERT INTO location VALUES (30, 30);
INSERT INTO location VALUES (31, 31);
INSERT INTO location VALUES (32, 32);
INSERT INTO location VALUES (33, 33);
INSERT INTO location VALUES (34, 34);
INSERT INTO location VALUES (35, 35);
INSERT INTO location VALUES (36, 36);
INSERT INTO location VALUES (37, 37);
INSERT INTO location VALUES (38, 38);
INSERT INTO location VALUES (39, 39);
INSERT INTO location VALUES (40, 40);
INSERT INTO location VALUES (41, 41);
INSERT INTO location VALUES (42, 42);
INSERT INTO location VALUES (43, 43);
INSERT INTO location VALUES (44, 44);
INSERT INTO location VALUES (45, 45);
INSERT INTO location VALUES (46, 46);
INSERT INTO location VALUES (47, 47);
INSERT INTO location VALUES (48, 48);
INSERT INTO location VALUES (49, 49);
INSERT INTO location VALUES (50, 50);
INSERT INTO location VALUES (51, 51);
INSERT INTO location VALUES (52, 52);
INSERT INTO location VALUES (53, 53);
INSERT INTO location VALUES (54, 54);
INSERT INTO location VALUES (55, 55);
INSERT INTO location VALUES (56, 56);
INSERT INTO location VALUES (58, 57);
INSERT INTO location VALUES (59, 58);
INSERT INTO location VALUES (60, 59);
INSERT INTO location VALUES (61, 60);
INSERT INTO location VALUES (62, 61);
INSERT INTO location VALUES (63, 62);
INSERT INTO location VALUES (64, 63);
INSERT INTO location VALUES (65, 64);
INSERT INTO location VALUES (66, 65);
INSERT INTO location VALUES (67, 66);
INSERT INTO location VALUES (68, 67);
INSERT INTO location VALUES (69, 68);
INSERT INTO location VALUES (70, 69);
INSERT INTO location VALUES (71, 70);
INSERT INTO location VALUES (72, 71);
INSERT INTO location VALUES (73, 72);
INSERT INTO location VALUES (74, 73);
INSERT INTO location VALUES (75, 74);
INSERT INTO location VALUES (76, 75);
INSERT INTO location VALUES (77, 76);
INSERT INTO location VALUES (78, 77);
INSERT INTO location VALUES (79, 78);
INSERT INTO location VALUES (80, 79);
INSERT INTO location VALUES (81, 80);
INSERT INTO location VALUES (82, 81);


/* market_user */

INSERT INTO market_user VALUES ('hasan', 'hasan', 1);
INSERT INTO market_user VALUES ('jim', 'jim', 2);
INSERT INTO market_user VALUES ('giada', 'giada', 3);
INSERT INTO market_user VALUES ('elvin', 'elvin', 4);
INSERT INTO market_user VALUES ('abdul', 'abdul', 5);
INSERT INTO market_user VALUES ('craig', 'craig', 6);
INSERT INTO market_user VALUES ('trace', 'trace', 7);
INSERT INTO market_user VALUES ('jena', 'jena', 8);
INSERT INTO market_user VALUES ('louie', 'louie', 9);
INSERT INTO market_user VALUES ('layne', 'layne', 10);
INSERT INTO market_user VALUES ('marian', 'marian', 11);
INSERT INTO market_user VALUES ('arielle', 'arielle', 12);
INSERT INTO market_user VALUES ('santiago', 'santiago', 13);
INSERT INTO market_user VALUES ('morgan', 'morgan', 14);
INSERT INTO market_user VALUES ('corine', 'corine', 15);
INSERT INTO market_user VALUES ('harold', 'harold', 16);
INSERT INTO market_user VALUES ('hamilton', 'hamilton', 17);
INSERT INTO market_user VALUES ('ulysses', 'ulysses', 18);
INSERT INTO market_user VALUES ('drew', 'drew', 19);
INSERT INTO market_user VALUES ('kelly', 'kelly', 20);
INSERT INTO market_user VALUES ('skylar', 'skylar', 21);
INSERT INTO market_user VALUES ('enrique', 'enrique', 22);
INSERT INTO market_user VALUES ('neta', 'neta', 23);
INSERT INTO market_user VALUES ('sharonda', 'sharonda', 24);
INSERT INTO market_user VALUES ('broderick', 'broderick', 25);
INSERT INTO market_user VALUES ('zechariah', 'zechariah', 26);
INSERT INTO market_user VALUES ('tillie', 'tillie', 27);
INSERT INTO market_user VALUES ('maureen', 'maureen', 28);
INSERT INTO market_user VALUES ('rachelle', 'rachelle', 29);
INSERT INTO market_user VALUES ('jasper', 'jasper', 30);
INSERT INTO market_user VALUES ('theresia', 'theresia', 31);
INSERT INTO market_user VALUES ('marlyn', 'marlyn', 32);
INSERT INTO market_user VALUES ('jefferson', 'jefferson', 33);
INSERT INTO market_user VALUES ('willis', 'willis', 34);
INSERT INTO market_user VALUES ('tania', 'tania', 35);
INSERT INTO market_user VALUES ('kaylynn', 'kaylynn', 36);
INSERT INTO market_user VALUES ('fern', 'fern', 37);
INSERT INTO market_user VALUES ('gertrude', 'gertrude', 38);
INSERT INTO market_user VALUES ('glenna', 'glenna', 39);
INSERT INTO market_user VALUES ('antoinette', 'antoinette', 40);
INSERT INTO market_user VALUES ('sydni', 'sydni', 41);
INSERT INTO market_user VALUES ('marlys', 'marlys', 42);
INSERT INTO market_user VALUES ('pearline', 'pearline', 43);
INSERT INTO market_user VALUES ('troy', 'troy', 44);
INSERT INTO market_user VALUES ('devon', 'devon', 45);
INSERT INTO market_user VALUES ('christin', 'christin', 46);
INSERT INTO market_user VALUES ('branson', 'branson', 47);
INSERT INTO market_user VALUES ('tena', 'tena', 48);
INSERT INTO market_user VALUES ('dominick', 'dominick', 49);
INSERT INTO market_user VALUES ('lincoln', 'lincoln', 50);
INSERT INTO market_user VALUES ('gearldine', 'gearldine', 51);
INSERT INTO market_user VALUES ('margie', 'margie', 52);
INSERT INTO market_user VALUES ('isabel', 'isabel', 53);
INSERT INTO market_user VALUES ('estevan', 'estevan', 54);
INSERT INTO market_user VALUES ('kennedi', 'kennedi', 55);
INSERT INTO market_user VALUES ('bailee', 'bailee', 56);
INSERT INTO market_user VALUES ('millicent', 'millicent', 57);
INSERT INTO market_user VALUES ('kaye', 'kaye', 58);
INSERT INTO market_user VALUES ('pearle', 'pearle', 59);
INSERT INTO market_user VALUES ('lucious', 'lucious', 60);
INSERT INTO market_user VALUES ('loyal', 'loyal', 61);
INSERT INTO market_user VALUES ('stephania', 'stephania', 62);
INSERT INTO market_user VALUES ('carter', 'carter', 63);
INSERT INTO market_user VALUES ('mammie', 'mammie', 64);
INSERT INTO market_user VALUES ('beverlee', 'beverlee', 65);
INSERT INTO market_user VALUES ('jason', 'jason', 66);
INSERT INTO market_user VALUES ('smith', 'smith', 67);
INSERT INTO market_user VALUES ('russel', 'russel', 68);
INSERT INTO market_user VALUES ('robin', 'robin', 69);
INSERT INTO market_user VALUES ('justin', 'justin', 70);
INSERT INTO market_user VALUES ('jacques', 'jacques', 71);
INSERT INTO market_user VALUES ('ryleigh', 'ryleigh', 72);
INSERT INTO market_user VALUES ('alice', 'alice', 73);
INSERT INTO market_user VALUES ('rosalind', 'rosalind', 74);
INSERT INTO market_user VALUES ('kimberli', 'kimberli', 75);
INSERT INTO market_user VALUES ('nichol', 'nichol', 76);
INSERT INTO market_user VALUES ('eloisa', 'eloisa', 77);
INSERT INTO market_user VALUES ('efrem', 'efrem', 78);
INSERT INTO market_user VALUES ('rosie', 'rosie', 79);
INSERT INTO market_user VALUES ('marlon', 'marlon', 80);
INSERT INTO market_user VALUES ('kristin', 'kristin', 81);


/* product */


INSERT INTO product VALUES (1, 'apple rose');
INSERT INTO product VALUES (2, 'brush cherry');
INSERT INTO product VALUES (3, 'mexican avocado');
INSERT INTO product VALUES (4, 'sea grape');
INSERT INTO product VALUES (5, 'kangaroo apple');
INSERT INTO product VALUES (6, 'mauritius raspberry');
INSERT INTO product VALUES (7, 'costa rica guava');
INSERT INTO product VALUES (8, 'sarvisberry');
INSERT INTO product VALUES (9, 'sunchoke');
INSERT INTO product VALUES (10, 'taro');
INSERT INTO product VALUES (11, 'ichang lemon');
INSERT INTO product VALUES (12, 'black elderberry');
INSERT INTO product VALUES (13, 'ciruela');
INSERT INTO product VALUES (14, 'american black gooseberry');
INSERT INTO product VALUES (15, 'champedek');
INSERT INTO product VALUES (16, 'emblic');
INSERT INTO product VALUES (17, 'black tamarind');
INSERT INTO product VALUES (18, 'otaheite orange');
INSERT INTO product VALUES (19, 'pepino');
INSERT INTO product VALUES (20, 'ananasnaja');
INSERT INTO product VALUES (21, 'wild orange');
INSERT INTO product VALUES (22, 'monkey tamarind');
INSERT INTO product VALUES (23, 'tangor');
INSERT INTO product VALUES (24, 'velvet vine');
INSERT INTO product VALUES (25, 'yellow sapote');
INSERT INTO product VALUES (26, 'white apple');
INSERT INTO product VALUES (27, 'siberian crab apple');
INSERT INTO product VALUES (28, 'may cherry');
INSERT INTO product VALUES (29, 'fig');
INSERT INTO product VALUES (30, 'south african cherry');
INSERT INTO product VALUES (31, 'western hackberry');
INSERT INTO product VALUES (32, 'marang');
INSERT INTO product VALUES (33, 'queen sago');
INSERT INTO product VALUES (34, 'maypop');
INSERT INTO product VALUES (35, 'indian fig');
INSERT INTO product VALUES (36, 'arkurbal');
INSERT INTO product VALUES (37, 'ceylon date palm');
INSERT INTO product VALUES (38, 'tuna');
INSERT INTO product VALUES (39, 'pepino dulce');
INSERT INTO product VALUES (40, 'cocoplum');
INSERT INTO product VALUES (41, 'wine palm');
INSERT INTO product VALUES (42, 'sweetberry');
INSERT INTO product VALUES (43, 'australian brush cherry');
INSERT INTO product VALUES (44, 'wild olive');
INSERT INTO product VALUES (45, 'lucmo');
INSERT INTO product VALUES (46, 'kaffir orange');
INSERT INTO product VALUES (47, 'acerola');
INSERT INTO product VALUES (48, 'brazil nut');
INSERT INTO product VALUES (49, 'beach cherry');
INSERT INTO product VALUES (50, 'tangelo');
INSERT INTO product VALUES (51, 'wild almond');
INSERT INTO product VALUES (52, 'oswego tea');
INSERT INTO product VALUES (53, 'japanese hackberry');
INSERT INTO product VALUES (54, 'matrimony vine');
INSERT INTO product VALUES (55, 'cinnamon');
INSERT INTO product VALUES (56, 'zubrovka');
INSERT INTO product VALUES (57, 'guavira mi');
INSERT INTO product VALUES (58, 'apple');
INSERT INTO product VALUES (59, 'raisin tree');
INSERT INTO product VALUES (60, 'mangaba');
INSERT INTO product VALUES (61, 'thimbleberry');
INSERT INTO product VALUES (62, 'japanese yew');
INSERT INTO product VALUES (63, 'jaboticaba');
INSERT INTO product VALUES (64, 'hog plum');
INSERT INTO product VALUES (65, 'sweet lime');
INSERT INTO product VALUES (66, 'plum mango');
INSERT INTO product VALUES (67, 'chinese olive');
INSERT INTO product VALUES (68, 'makopa');
INSERT INTO product VALUES (69, 'panama berry');
INSERT INTO product VALUES (70, 'crato passion fruit');
INSERT INTO product VALUES (71, 'kwai muk');
INSERT INTO product VALUES (72, 'yucca');


/* sale */

INSERT INTO sale VALUES (1, 1, 1, 2, '2022-01-14');
INSERT INTO sale VALUES (2, 1, 1, 3, '2022-01-14');
INSERT INTO sale VALUES (3, 4, 21, 3, '2022-01-14');
INSERT INTO sale VALUES (4, 6, 54, 1, '2022-01-14');
INSERT INTO sale VALUES (5, 9, 32, 5, '2022-01-14');
INSERT INTO sale VALUES (6, 9, 13, 1, '2022-01-14');
INSERT INTO sale VALUES (7, 11, 65, 4, '2022-01-14');
INSERT INTO sale VALUES (8, 11, 71, 6, '2022-01-14');
INSERT INTO sale VALUES (9, 15, 5, 7, '2022-01-14');
INSERT INTO sale VALUES (10, 51, 50, 3, '2022-01-14');
INSERT INTO sale VALUES (11, 51, 63, 2, '2022-01-14');


/* seller */

INSERT INTO seller VALUES (1, 'hasan', 'yunus');
INSERT INTO seller VALUES (2, 'Jim', 'FOGHT');
INSERT INTO seller VALUES (3, 'Giada', 'LINSTER');
INSERT INTO seller VALUES (4, 'Elvin', 'BOUFFARD');
INSERT INTO seller VALUES (5, 'Abdul', 'CAMBERN');
INSERT INTO seller VALUES (6, 'Craig', 'HEBBELER');
INSERT INTO seller VALUES (7, 'Trace', 'BRAZO');
INSERT INTO seller VALUES (8, 'Jena', 'BILLSTROM');
INSERT INTO seller VALUES (9, 'Louie', 'NER');
INSERT INTO seller VALUES (10, 'Layne', 'WISHARD');
INSERT INTO seller VALUES (11, 'Marian', 'DAYRIT');
INSERT INTO seller VALUES (12, 'Arielle', 'SIBILIO');
INSERT INTO seller VALUES (13, 'Santiago', 'KINGEN');
INSERT INTO seller VALUES (14, 'Morgan', 'ELLERTON');
INSERT INTO seller VALUES (15, 'Corine', 'CHARMOLI');
INSERT INTO seller VALUES (16, 'Harold', 'MARISCAL');
INSERT INTO seller VALUES (17, 'Hamilton', 'BARSANTI');
INSERT INTO seller VALUES (18, 'Ulysses', 'GARISS');
INSERT INTO seller VALUES (19, 'Drew', 'QUILL');
INSERT INTO seller VALUES (20, 'Kelly', 'RIGEL');
INSERT INTO seller VALUES (21, 'Skylar', 'ROSSINO');
INSERT INTO seller VALUES (22, 'Enrique', 'DENATO');
INSERT INTO seller VALUES (23, 'Neta', 'QUINT');
INSERT INTO seller VALUES (24, 'Sharonda', 'DEFRANZO');
INSERT INTO seller VALUES (25, 'Broderick', 'STOTLAR');
INSERT INTO seller VALUES (26, 'Zechariah', 'RAZMUS');
INSERT INTO seller VALUES (27, 'Tillie', 'HEY');
INSERT INTO seller VALUES (28, 'Maureen', 'TOPF');
INSERT INTO seller VALUES (29, 'Rachelle', 'DERIAN');
INSERT INTO seller VALUES (30, 'Jasper', 'SELLARD');
INSERT INTO seller VALUES (31, 'Theresia', 'GUCKENBERGER');
INSERT INTO seller VALUES (32, 'Marlyn', 'HRDY');
INSERT INTO seller VALUES (33, 'Jefferson', 'HARTLING');
INSERT INTO seller VALUES (34, 'Willis', 'LAUBNER');
INSERT INTO seller VALUES (35, 'Tania', 'TORELLA');
INSERT INTO seller VALUES (36, 'Kaylynn', 'SUGITA');
INSERT INTO seller VALUES (37, 'Fern', 'CARKEEK');
INSERT INTO seller VALUES (38, 'Gertrude', 'PRISCO');
INSERT INTO seller VALUES (39, 'Glenna', 'COSTEIRA');
INSERT INTO seller VALUES (40, 'Antoinette', 'LACARTE');
INSERT INTO seller VALUES (41, 'Sydni', 'SWIGER');
INSERT INTO seller VALUES (42, 'Marlys', 'HOUDYSHELL');
INSERT INTO seller VALUES (43, 'Pearline', 'KUPSCH');
INSERT INTO seller VALUES (44, 'Troy', 'TALLMADGE');
INSERT INTO seller VALUES (45, 'Devon', 'CUSA');
INSERT INTO seller VALUES (46, 'Christin', 'LOVIO');
INSERT INTO seller VALUES (47, 'Branson', 'SCOLNICK');
INSERT INTO seller VALUES (48, 'Tena', 'KAEHLER');
INSERT INTO seller VALUES (49, 'Dominick', 'ELLERBROOK');
INSERT INTO seller VALUES (50, 'Lincoln', 'CIGNETTI');
INSERT INTO seller VALUES (51, 'Gearldine', 'FARANO');
INSERT INTO seller VALUES (52, 'Margie', 'LUCCHETTI');
INSERT INTO seller VALUES (53, 'Isabel', 'STANDRIDGE');
INSERT INTO seller VALUES (54, 'Estevan', 'STURM');
INSERT INTO seller VALUES (55, 'Kennedi', 'GRASSROPE');
INSERT INTO seller VALUES (56, 'Bailee', 'HOFSTEDT');
INSERT INTO seller VALUES (57, 'Millicent', 'SCHEURICH');
INSERT INTO seller VALUES (58, 'Kaye', 'CENTILLI');
INSERT INTO seller VALUES (59, 'Pearle', 'KARRELS');
INSERT INTO seller VALUES (60, 'Lucious', 'HUBAL');
INSERT INTO seller VALUES (61, 'Loyal', 'MONRREAL');
INSERT INTO seller VALUES (62, 'Stephania', 'GATLEY');
INSERT INTO seller VALUES (63, 'Carter', 'HAVEKOST');
INSERT INTO seller VALUES (64, 'Mammie', 'ROLNICK');
INSERT INTO seller VALUES (65, 'Beverlee', 'LYSAK');
INSERT INTO seller VALUES (66, 'Jason', 'THEILACKER');
INSERT INTO seller VALUES (67, 'Smith', 'SYNN');
INSERT INTO seller VALUES (68, 'Russel', 'VANSCOYOC');
INSERT INTO seller VALUES (69, 'Robin', 'PAARLBERG');
INSERT INTO seller VALUES (70, 'Justin', 'KUHARIK');
INSERT INTO seller VALUES (71, 'Jacques', 'TOLCHINSKY');
INSERT INTO seller VALUES (72, 'Ryleigh', 'CARVANA');
INSERT INTO seller VALUES (73, 'Alice', 'WORMACK');
INSERT INTO seller VALUES (74, 'Rosalind', 'KIEMELE');
INSERT INTO seller VALUES (75, 'Kimberli', 'NIEHUS');
INSERT INTO seller VALUES (76, 'Nichol', 'TATMAN');
INSERT INTO seller VALUES (77, 'Eloisa', 'UNTALAN');
INSERT INTO seller VALUES (78, 'Efrem', 'STROCKBINE');
INSERT INTO seller VALUES (79, 'Rosie', 'DARST');
INSERT INTO seller VALUES (80, 'Marlon', 'FLENER');
INSERT INTO seller VALUES (81, 'Kristin', 'CIONGOLI');


/* stock */

INSERT INTO stock VALUES (44, 45, 24, 6);
INSERT INTO stock VALUES (61, 16, 22, 13);
INSERT INTO stock VALUES (2, 19, 5, 6);
INSERT INTO stock VALUES (69, 11, 14, 4);
INSERT INTO stock VALUES (37, 46, 9, 7);
INSERT INTO stock VALUES (80, 25, 24, 12);
INSERT INTO stock VALUES (52, 23, 1, 7);
INSERT INTO stock VALUES (19, 58, 8, 7);
INSERT INTO stock VALUES (9, 2, 24, 3);
INSERT INTO stock VALUES (59, 61, 8, 17);
INSERT INTO stock VALUES (73, 34, 24, 4);
INSERT INTO stock VALUES (71, 5, 24, 10);
INSERT INTO stock VALUES (8, 46, 11, 17);
INSERT INTO stock VALUES (68, 40, 8, 12);
INSERT INTO stock VALUES (15, 49, 9, 10);
INSERT INTO stock VALUES (81, 28, 12, 17);
INSERT INTO stock VALUES (15, 69, 12, 7);
INSERT INTO stock VALUES (37, 31, 17, 9);
INSERT INTO stock VALUES (46, 25, 23, 15);
INSERT INTO stock VALUES (31, 31, 16, 11);
INSERT INTO stock VALUES (12, 41, 21, 3);
INSERT INTO stock VALUES (55, 9, 22, 7);
INSERT INTO stock VALUES (20, 34, 17, 4);
INSERT INTO stock VALUES (67, 16, 5, 17);
INSERT INTO stock VALUES (20, 57, 12, 13);
INSERT INTO stock VALUES (51, 60, 16, 6);
INSERT INTO stock VALUES (76, 68, 18, 6);
INSERT INTO stock VALUES (30, 28, 12, 14);
INSERT INTO stock VALUES (78, 29, 5, 15);
INSERT INTO stock VALUES (70, 68, 7, 3);
INSERT INTO stock VALUES (49, 27, 22, 10);
INSERT INTO stock VALUES (44, 43, 18, 15);
INSERT INTO stock VALUES (8, 66, 23, 6);
INSERT INTO stock VALUES (19, 52, 13, 12);
INSERT INTO stock VALUES (36, 59, 11, 17);
INSERT INTO stock VALUES (41, 53, 16, 8);
INSERT INTO stock VALUES (35, 38, 13, 5);
INSERT INTO stock VALUES (11, 36, 2, 9);
INSERT INTO stock VALUES (79, 29, 23, 4);
INSERT INTO stock VALUES (71, 8, 6, 8);
INSERT INTO stock VALUES (14, 36, 14, 12);
INSERT INTO stock VALUES (67, 44, 17, 17);
INSERT INTO stock VALUES (70, 38, 6, 8);
INSERT INTO stock VALUES (8, 40, 11, 6);
INSERT INTO stock VALUES (11, 61, 1, 16);
INSERT INTO stock VALUES (74, 10, 24, 15);
INSERT INTO stock VALUES (30, 44, 12, 6);
INSERT INTO stock VALUES (52, 6, 8, 8);
INSERT INTO stock VALUES (18, 10, 2, 15);
INSERT INTO stock VALUES (80, 30, 14, 17);
INSERT INTO stock VALUES (10, 68, 22, 15);
INSERT INTO stock VALUES (6, 18, 11, 15);
INSERT INTO stock VALUES (5, 27, 12, 3);
INSERT INTO stock VALUES (46, 66, 19, 17);
INSERT INTO stock VALUES (60, 18, 17, 12);
INSERT INTO stock VALUES (43, 59, 4, 7);
INSERT INTO stock VALUES (80, 57, 23, 11);
INSERT INTO stock VALUES (75, 44, 9, 6);
INSERT INTO stock VALUES (65, 14, 11, 9);
INSERT INTO stock VALUES (21, 46, 24, 7);
INSERT INTO stock VALUES (18, 20, 19, 15);
INSERT INTO stock VALUES (57, 18, 19, 10);
INSERT INTO stock VALUES (24, 9, 12, 10);
INSERT INTO stock VALUES (37, 67, 1, 8);
INSERT INTO stock VALUES (14, 31, 13, 15);
INSERT INTO stock VALUES (33, 72, 23, 17);
INSERT INTO stock VALUES (75, 38, 15, 11);
INSERT INTO stock VALUES (41, 50, 19, 5);
INSERT INTO stock VALUES (73, 57, 21, 6);
INSERT INTO stock VALUES (15, 53, 6, 6);
INSERT INTO stock VALUES (43, 25, 7, 5);
INSERT INTO stock VALUES (77, 8, 6, 17);
INSERT INTO stock VALUES (43, 68, 22, 17);
INSERT INTO stock VALUES (68, 33, 9, 8);
INSERT INTO stock VALUES (45, 44, 16, 16);
INSERT INTO stock VALUES (36, 43, 17, 16);
INSERT INTO stock VALUES (19, 34, 3, 13);
INSERT INTO stock VALUES (60, 55, 9, 8);
INSERT INTO stock VALUES (64, 31, 15, 14);
INSERT INTO stock VALUES (57, 22, 22, 11);
INSERT INTO stock VALUES (31, 51, 12, 12);
INSERT INTO stock VALUES (47, 5, 11, 5);
INSERT INTO stock VALUES (15, 2, 15, 13);
INSERT INTO stock VALUES (27, 18, 23, 6);
INSERT INTO stock VALUES (5, 46, 20, 14);
INSERT INTO stock VALUES (71, 43, 24, 13);
INSERT INTO stock VALUES (13, 9, 18, 14);
INSERT INTO stock VALUES (28, 50, 20, 13);
INSERT INTO stock VALUES (32, 49, 9, 8);
INSERT INTO stock VALUES (68, 55, 18, 6);
INSERT INTO stock VALUES (2, 3, 9, 10);
INSERT INTO stock VALUES (11, 26, 15, 10);
INSERT INTO stock VALUES (46, 30, 15, 14);
INSERT INTO stock VALUES (21, 4, 9, 14);
INSERT INTO stock VALUES (24, 54, 18, 10);
INSERT INTO stock VALUES (28, 43, 10, 5);
INSERT INTO stock VALUES (17, 3, 17, 10);
INSERT INTO stock VALUES (30, 72, 11, 5);
INSERT INTO stock VALUES (26, 5, 2, 17);
INSERT INTO stock VALUES (21, 59, 23, 16);
INSERT INTO stock VALUES (53, 1, 9, 4);
INSERT INTO stock VALUES (19, 18, 15, 17);
INSERT INTO stock VALUES (23, 13, 23, 3);
INSERT INTO stock VALUES (50, 56, 15, 4);
INSERT INTO stock VALUES (77, 49, 5, 16);
INSERT INTO stock VALUES (5, 14, 5, 15);
INSERT INTO stock VALUES (79, 30, 3, 13);
INSERT INTO stock VALUES (73, 67, 14, 14);
INSERT INTO stock VALUES (37, 8, 13, 10);
INSERT INTO stock VALUES (62, 45, 20, 14);
INSERT INTO stock VALUES (78, 60, 2, 15);
INSERT INTO stock VALUES (48, 18, 13, 6);
INSERT INTO stock VALUES (35, 68, 10, 13);
INSERT INTO stock VALUES (26, 14, 2, 8);
INSERT INTO stock VALUES (19, 50, 7, 14);
INSERT INTO stock VALUES (69, 57, 1, 9);
INSERT INTO stock VALUES (36, 3, 14, 15);
INSERT INTO stock VALUES (5, 24, 20, 11);
INSERT INTO stock VALUES (14, 12, 9, 16);
INSERT INTO stock VALUES (71, 49, 21, 4);
INSERT INTO stock VALUES (42, 24, 16, 3);
INSERT INTO stock VALUES (56, 49, 2, 4);
INSERT INTO stock VALUES (69, 62, 1, 15);
INSERT INTO stock VALUES (78, 61, 10, 3);
INSERT INTO stock VALUES (80, 33, 15, 11);
INSERT INTO stock VALUES (21, 27, 6, 11);
INSERT INTO stock VALUES (58, 55, 22, 4);
INSERT INTO stock VALUES (63, 20, 23, 12);
INSERT INTO stock VALUES (25, 19, 4, 6);
INSERT INTO stock VALUES (74, 17, 19, 10);
INSERT INTO stock VALUES (48, 35, 18, 6);
INSERT INTO stock VALUES (54, 34, 8, 13);
INSERT INTO stock VALUES (23, 23, 2, 11);
INSERT INTO stock VALUES (19, 37, 15, 7);
INSERT INTO stock VALUES (5, 56, 18, 15);
INSERT INTO stock VALUES (19, 61, 3, 6);
INSERT INTO stock VALUES (21, 29, 23, 13);
INSERT INTO stock VALUES (46, 36, 19, 11);
INSERT INTO stock VALUES (57, 42, 2, 17);
INSERT INTO stock VALUES (81, 32, 1, 5);
INSERT INTO stock VALUES (71, 63, 11, 7);
INSERT INTO stock VALUES (22, 58, 17, 13);
INSERT INTO stock VALUES (54, 11, 15, 13);
INSERT INTO stock VALUES (1, 71, 20, 12);
INSERT INTO stock VALUES (5, 50, 12, 8);
INSERT INTO stock VALUES (27, 10, 10, 10);
INSERT INTO stock VALUES (11, 69, 21, 11);
INSERT INTO stock VALUES (23, 34, 12, 4);
INSERT INTO stock VALUES (9, 15, 19, 15);
INSERT INTO stock VALUES (13, 35, 12, 14);
INSERT INTO stock VALUES (36, 64, 2, 14);
INSERT INTO stock VALUES (45, 63, 23, 8);
INSERT INTO stock VALUES (28, 64, 12, 13);
INSERT INTO stock VALUES (26, 8, 1, 8);
INSERT INTO stock VALUES (37, 59, 9, 9);
INSERT INTO stock VALUES (8, 17, 9, 7);
INSERT INTO stock VALUES (48, 6, 23, 3);
INSERT INTO stock VALUES (65, 58, 16, 8);
INSERT INTO stock VALUES (64, 52, 5, 12);
INSERT INTO stock VALUES (54, 10, 8, 10);
INSERT INTO stock VALUES (12, 47, 19, 5);
INSERT INTO stock VALUES (15, 66, 2, 8);
INSERT INTO stock VALUES (65, 20, 22, 17);
INSERT INTO stock VALUES (38, 19, 18, 6);
INSERT INTO stock VALUES (29, 64, 18, 8);
INSERT INTO stock VALUES (80, 9, 3, 4);
INSERT INTO stock VALUES (47, 12, 12, 13);
INSERT INTO stock VALUES (12, 34, 3, 4);
INSERT INTO stock VALUES (15, 55, 14, 16);
INSERT INTO stock VALUES (46, 29, 14, 7);
INSERT INTO stock VALUES (7, 19, 12, 5);
INSERT INTO stock VALUES (80, 41, 6, 8);
INSERT INTO stock VALUES (53, 12, 16, 17);
INSERT INTO stock VALUES (48, 39, 22, 10);
INSERT INTO stock VALUES (12, 54, 6, 5);
INSERT INTO stock VALUES (4, 21, 20, 10);
INSERT INTO stock VALUES (6, 54, 8, 9);
INSERT INTO stock VALUES (9, 32, 16, 9);
INSERT INTO stock VALUES (9, 13, 12, 15);
INSERT INTO stock VALUES (11, 65, 7, 5);
INSERT INTO stock VALUES (11, 71, 15, 12);
INSERT INTO stock VALUES (15, 5, 9, 11);
INSERT INTO stock VALUES (51, 63, 3, 12);
INSERT INTO stock VALUES (72, 3, 23, 7);
INSERT INTO stock VALUES (24, 47, 12, 4);
INSERT INTO stock VALUES (25, 5, 7, 6);
INSERT INTO stock VALUES (63, 59, 23, 15);
INSERT INTO stock VALUES (9, 28, 11, 8);
INSERT INTO stock VALUES (69, 58, 13, 6);
INSERT INTO stock VALUES (76, 46, 14, 3);
INSERT INTO stock VALUES (42, 67, 21, 5);
INSERT INTO stock VALUES (4, 22, 20, 4);
INSERT INTO stock VALUES (29, 12, 24, 10);
INSERT INTO stock VALUES (56, 19, 14, 15);
INSERT INTO stock VALUES (48, 4, 2, 5);
INSERT INTO stock VALUES (1, 1, 3, 12);
INSERT INTO stock VALUES (51, 50, 3, 14);